### PR TITLE
daemon: Better handle 'unknown' state for certain operations

### LINKED ISSUE #644: No way to deal with UNKNOWN instances
Whenever an instance ends up in `UNKNOWN` state (i.e. it's not responded after starting), there doesn't seem to be a way to deal with it within a reasonable amount of time.

Especially with #632 this means the daemon goes into a locked state for extended amounts of time.

I suppose we should be more forceful with instances that go into the `UNKNOWN`.

Fixing #643 will greatly improve this situation, but it won't come very soon.

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #644

### CODE REVIEW

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
Hmm?

bors try

**Comment by Saviq** [comment]
How about now?

bors try

**Comment by townsend2010** [comment]
bors try-

**Comment by townsend2010** [comment]
bors ping

**Comment by townsend2010** [comment]
bors try

**Comment by gerboland** [comment]
bors try

**Comment by Saviq** [comment]
try-

**Comment by Saviq** [comment]
bors tr-

**Comment by Saviq** [comment]
bors try-

**Comment by townsend2010** [comment]
@gerboland,

I added tests (although it didn't help coverage).  Are you good with this?

**Pull request merged**
