### PR TITLE
Fix absent settings dir and consequent inotify watch failure

### PR DESCRIPTION
**Pull request by ricab**
Fixes absent settings directory, which prevented the daemon from initializing its settings file to watch for changes. Also drops XDG dir creation in the snap launchers (see corresponding commit msg). The `Settings` can create its files on its own (relying on `QSettings`) for that.

### CODE REVIEW

**Comment by Saviq** [comment]
The launchers for `multipass` and `multipass-gui` are now NOOP, just drop them please.

**Comment by ricab** [comment]
@Saviq Thanks for noticing that, I just pushed the fix. BTW, how can I check the results of snap testing you recently added? Is it automatic in our existing CI?

**Comment by Saviq** [comment]
@ricab yeah, it's just an additional step to the `RelWithDebInfo` job, [here's an example](https://travis-ci.org/CanonicalLtd/multipass/jobs/551938661#L3465) from the previous run of this PR.

**Comment by ricab** [comment]
OK got it, thanks.

**Pull request merged**
