### PR TITLE
 [snap] switch to core18 base (Fixes #598)

### LINKED ISSUE #598: switch to core18 base
Most of this already happens in #596, but there's a twist: any instances suspended or running on the core16 version of the snap won't be resume-able on the core18 version.

`snapd` does not give us much notice about the refresh, the only thing we could do is to fail the `pre-refresh` hook, but without [epochs' stepped upgrades](https://forum.snapcraft.io/t/epochs-stepped-upgrades/1757) that snap revision may be skipped, and in fact [would be for sure](https://forum.snapcraft.io/t/how-to-cause-a-snap-rollback/9848/4), if we failed `pre-refresh`.

The only option for safe, no-user-intervention transition would be to convert/upgrade the snapshot, but it's unclear whether that's possible.

Plan of record:
- create a `core16` snap branch and keep the latest `core16`-based release there
- add a `start` option allowing for the user to discard the snapshot
- detect the incompatible snapshot either by its metadata or the `qmp` error and mark the instance appropriately
- inform the user of the problem and how they can solve it (refresh to `core16`, shut all instances down, refresh back)

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by Saviq** [comment]
This is a resubmit of #591.

I left
```
The 'qemu' part needs the following libraries that are not included in the snap or base: 
usr/lib/x86_64-linux-gnu/libGL.so.1
usr/lib/x86_64-linux-gnu/libGLU.so.1
usr/lib/x86_64-linux-gnu/libGLX.so.0
usr/lib/x86_64-linux-gnu/libGLdispatch.so.0
These dependencies can be satisfied via more stage-packages, more parts, or content sharing.
```
On purpose, since we don't use GL in our VMs.

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
Reopened targetting into `master`.

**Comment by Saviq** [comment]
There's a new development… `snapd` [has a bug](https://bugs.launchpad.net/snappy/+bug/1819875) when transitioning services between different bases. It's recommended that we wait for this bug to be fixed before we do the switch.

**Comment by Saviq** [comment]
@townsend2010 this is ready for another look.

**Comment by Saviq** [comment]
Snap available in the `edge/core18` channel.

**Comment by townsend2010** [comment]
Actually, since it's Friday, let's wait until Monday before landing :grin:

**Comment by Saviq** [comment]
It's only going into `edge`, it's _fine_ ;)

bors r=townsend2010

**Comment by townsend2010** [comment]
lol, ok:)

**Pull request merged**
