### PR TITLE
 sshfs_mount: Recover mounts when sshfs exits for unexpected reasons 

### LINKED ISSUE #509: [mount] multipassd fails to notice sshfs going away inside the instance
Steps:
- create a mount
- kill sshfs inside the instance
- `multipass info --all`

Expected:
- an error logged in the multipassd log
- restarting sshfs

Current:
- multipassd thinks the mount is still going

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #509

### CODE REVIEW

**Comment by Saviq** [comment]
Does that relate to #936 do you think?

**Comment by townsend2010** [comment]
@Saviq 
> Does that relate to #936 do you think?

It _might_...

**Comment by townsend2010** [comment]
@gerboland,

I'm not sure where you think I'm polling for the `sshfs` process inside the VM on each `sshfs` event.  I only check for the `sshfs` process if `sftp_get_client_message` returns a `NULL` client message, indicating that something bad happened to the connection.

**Comment by gerboland** [comment]
> @gerboland,
> 
> I'm not sure where you think I'm polling for the `sshfs` process inside the VM on each `sshfs` event. I only check for the `sshfs` process if `sftp_get_client_message` returns a `NULL` client message, indicating that something bad happened to the connection.

Ah ok, I hadn't noticed that null check was so important.

**Comment by townsend2010** [comment]
> Ah ok, I hadn't noticed that null check was so important.

Ok, good, I hoped I wasn't missing something :smile:

**Comment by townsend2010** [comment]
@gerboland,

I'm not sure of the exact reasons why `sshfs` goes away in the instance, but I suspect it's etiher crashing or erroring out.

The archive version of `libfuse` and `sshfs` are quite old, so I have another project at https://github.com/CanonicalLtd/multipass-sshfs that builds a snap package using upstream `libfuse` and `sshfs`.  This works quite well and should resolve many crashing/error issues.  I'm just waiting for the `bare` base to be promoted to stable and then support for that to be merged into snapcraft.  That way, the whole `core18` snap will not need to be downloaded and installed when installing the `multipass-sshfs` snap.

**Pull request merged**
