### PR TITLE
ssh_session: Increase session timeout to 20s to account for busy VM's

### LINKED ISSUE #394: info failed: ssh: Timeout connecting to (IP)
I'm doing a build via `snapcraft` and `SNAPCRAFT_BUILD_ENVIRONMENT=multipass`. I want to poke about in the VM while it's building, as it takes ages and I want to see what it's doing.

I am unable to get in.

```
alan@KinkPad-K450:~/src/che$ multipass list | grep che
snapcraft-che           RUNNING     10.185.163.90    Ubuntu 18.04 LTS
alan@KinkPad-K450:~/src/che$ multipass shell snapcraft-che
shell failed: ssh: Timeout connecting to 10.185.163.90
alan@KinkPad-K450:~/src/che$ multipass info snapcraft-che
info failed: ssh: Timeout connecting to 10.185.163.90
```

### LINKED ISSUE #419: Some internal commands to the instance time out too quickly
When busy (host or instance), the instance might not be replying quickly enough, resulting in missing info, or worse, failed mounts.

This got found by running two (or more) snapcraft runs on the same host:

```
$ SNAPCRAFT_BUILD_ENVIRONMENT=multipass snapcraft
```

While that is going, trying to `multipass info --all` results in a combination of:
```
2018-09-28T12:02:44Z multipassd[12591]: no output after running 'cat /proc/loadavg | cut -d ' ' -f1-3'
2018-09-28T12:02:44Z multipassd[12591]: no output after running 'df --output=size `awk '$2 == "/" { print $1 }' /proc/mounts` -B1 | sed 1d'
2018-09-28T12:02:45Z multipassd[12591]: no output after running 'lsb_release -ds'
2018-09-28T12:02:47Z multipassd[12591]: no output after running 'free -b | sed '1d;3d' | awk '{printf $3}''
2018-09-28T12:02:47Z multipassd[12591]: no output after running 'free -b | sed '1d;3d' | awk '{printf $2}''
2018-09-28T12:02:47Z multipassd[12591]: no output after running 'df --output=used `awk '$2 == "/" { print $1 }' /proc/mounts` -B1 | sed 1d'
2018-09-28T12:02:47Z multipassd[12591]: no output after running 'lsb_release -ds'
```

Mounts tend to fail, too:
```
$ while true; do multipass mount $PWD snapcraft-snapcraft; multipass umount snapcraft-snapcraft; done
mount failed: The following errors occurred:
error mounting "/home/michal/dev/canonical/snapcore/snapcraft": stoi
```

And straight up shell:
```
$ time multipass sh snapcraft-multipass
shell failed: ssh connection failed: 'Timeout connecting to 10.225.180.86'
multipass sh snapcraft-multipass  0,05s user 0,02s system 5% cpu 1,113 total
```

It times out after a second? We should increase that timeout at least, and maybe be smarter about it and have some fail-over with a longer timeout?

### PR DESCRIPTION
**Pull request by townsend2010**
Fixes #394, Fixes #419

### CODE REVIEW

**Comment by albaguirre** [comment]
I think you mean fixes #394?

**Comment by Saviq** [comment]
Yes please.
bors r+

**Comment by townsend2010** [comment]
Ahh, right typo'd the fix number...now that is fixed:)

**Comment by townsend2010** [comment]
bors r=Saviq

**Comment by albaguirre** [comment]
I think taking a timeout value in the constructor (in std::chrono::milliseconds is better) with a second default constructor that does not take any parameters but defaults to 20 secs.

This way, in wait for wait_for_ssh, we can then use a std::chrono::seconds(1) timeout, to avoid blocking too long.

**Comment by townsend2010** [comment]
@albaguirre Ack, will fix this up for that case.

**Comment by townsend2010** [comment]
@albaguirre,
Fixed this up as you suggested:)

**Comment by townsend2010** [comment]
bors r=Saviq

**Comment by townsend2010** [comment]
Bah, bors timed out for whatever reason, will merge manually...

**Pull request merged**
