### PR TITLE
[proc] Mention program name in process error

### LINKED ISSUE #613: Error message misleading when qemu runtime dependency is not satisfied
As discussed in (unrelated) issue #578, trying to launch an instance with multipass when the qemu-system command is not available results in a misleading error message:

```
$ multipass launch -vvv b
launch failed: Cannot resize instance image
```

Highest verbosity logs were not useful either.

### PR DESCRIPTION
**Pull request by ricab**
Add the program name to process error messages. This makes it easier to
quickly understand what process failed. Fixes #613 as a particular case.

### CODE REVIEW

**Comment by ricab** [comment]
Sure. You mean that the program name is in the error message? Or something more specific?

**Comment by Saviq** [comment]
Really just that `::error_string` returns the expected :)

**Comment by ricab** [comment]
@Saviq just added a few tests, are you ok with these?

**Comment by Saviq** [comment]
Yup, thanks!

bors r+

**Pull request merged**
