### PR TITLE
qemu: Save qemu "machine type" as metadata for the instance

### LINKED ISSUE #598: switch to core18 base
Most of this already happens in #596, but there's a twist: any instances suspended or running on the core16 version of the snap won't be resume-able on the core18 version.

`snapd` does not give us much notice about the refresh, the only thing we could do is to fail the `pre-refresh` hook, but without [epochs' stepped upgrades](https://forum.snapcraft.io/t/epochs-stepped-upgrades/1757) that snap revision may be skipped, and in fact [would be for sure](https://forum.snapcraft.io/t/how-to-cause-a-snap-rollback/9848/4), if we failed `pre-refresh`.

The only option for safe, no-user-intervention transition would be to convert/upgrade the snapshot, but it's unclear whether that's possible.

Plan of record:
- create a `core16` snap branch and keep the latest `core16`-based release there
- add a `start` option allowing for the user to discard the snapshot
- detect the incompatible snapshot either by its metadata or the `qmp` error and mark the instance appropriately
- inform the user of the problem and how they can solve it (refresh to `core16`, shut all instances down, refresh back)

### PR DESCRIPTION
**Pull request by townsend2010**
This is to allow resuming from suspend when changing QEMU versions in the snap.

Fixes #598

### CODE REVIEW

**Comment by townsend2010** [comment]
@Saviq,

The `metadata` is not qemu specific per se.  It is *any* data that a specific backend wants to put in there, as shown in that `QemuVirtualMachine` is the one setting it and telling the daemon to save it.  

For example, the HyperKit backend (or any other backend) could potentially set any metadata it wants in there, just as long as it's sent as a JSON object.

That said, there needs to be some way to persist the data, so when `multipassd` comes up after a restart, the backend can get that saved data.  And unless we totally want each backend to have direct access to the json file, then I think the way I've implemented it is the most straight forward and safest way to go.

**Comment by townsend2010** [comment]
@Saviq,

Just read your edit.  I'm not introducing anything qemu specific to the generic classes.  It's a QJsonObject that can contain *anything* the backend wants it to contain.

**Comment by Saviq** [comment]
> Still, think it prudent to introduce all the qemu-specific bits after all to the generic classes?

I had (some food and) another look and I agree with your replies :)

I suppose it's not weird to require that the metadata is JSON, if the on-disk data format is that anyway. Only other option would be to employ some kind of marshalling, which doesn't seem to make much sense when it's not public API anyway.

**Comment by townsend2010** [comment]
Right, I chose JSON since it's already JSON:)   Glad you had food and agree with me now;)

**Comment by townsend2010** [comment]
Another issue is that the `QTemporaryFile` I use to output `-dump-vmstate` does not work inside a snap.  Need to fix that as well.

**Comment by townsend2010** [comment]
Ok, it wasn't the QTemporaryFile after all, but I found the issue regardless and fixed it.  This should be ready again for review.

**Comment by Saviq** [comment]
bors r+

Thanks!

**Pull request merged**
