### PR TITLE
Extract instance creation from launch

### PR DESCRIPTION
**Pull request by ricab**
Place instance creation in a separate method, to prepare the way to create without launching.

### CODE REVIEW

**Comment by Saviq** [comment]
So a draft WP doesn't run checks, wonder if `bors` will act on it though?

bors try

**Comment by Saviq** [comment]
So `bors` does work, travis ignores it altogether though.

**Comment by Saviq** [comment]
FWIW, this failed b/c is a PR into `pet-env`, not `master`, and it lacks the latest commits from there.

**Comment by ricab** [comment]
Thanks @Saviq. Yeah I haven't rebased this on master after the PR that fixes the failing test.

**Comment by ricab** [comment]
Here something discussing absent Travis CI in draft PRs: https://travis-ci.community/t/draft-pull-requests-not-being-built/2434/5

**Comment by ricab** [comment]
bors try

**Comment by ricab** [comment]
bors try-

**Comment by ricab** [comment]
Just changed base back to master, to avoid having to manually rebase.

bors try

**Comment by ricab** [comment]
bors try

**Comment by ricab** [comment]
bors try

**Comment by ricab** [comment]
This "draft" feature does not seem to be working very well yet. In particular, it is not showing checks even after turning it into a PR. So closing and opening a new one.

**Pull request closed without merging**
