### PR TITLE
[snap] snapcraft.yaml cleanup and improvements

### PR DESCRIPTION
**Pull request by Saviq**
- move to `base:`-enabled `snapcraft.yaml`
- improve snap metadata
- use `snapcraft --use-lxd` on travis
- add missing package

### CODE REVIEW

**Comment by Saviq** [comment]
Building on Launchpad here, too:

**Comment by townsend2010** [comment]
Ok, any instances or containers left from previous builds need to be purged first.  After doing that, it seems to be working.

On another note, CI says it is still waiting, but the builds completed successfully over an hour ago.  I wonder what is going on there?

**Comment by townsend2010** [comment]
Try again

bors r+

**Comment by townsend2010** [comment]
Try one more time

bors r+

**Comment by Saviq** [comment]
This might actually be highlighting an issue in `snapcraft`'s LXD support, although the trace in question is from `cloud-init` itself.

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
Hmm `bors` seems to have gotten in a fit with this PR… The `try` completed [here](https://travis-ci.org/CanonicalLtd/multipass/builds/542130675).

Let's try one more time:

bors r=townsend2010

**Comment by Saviq** [comment]
And this time it was Mac

bors r=townsend2010

**Comment by Saviq** [comment]
It completed fine [here](https://travis-ci.org/CanonicalLtd/multipass/builds/542185086) but `bors` seems oblivious… Merging.

**Pull request merged**
