### PR TITLE
Document the (CPU|disk|memory) defaults in `multipass help launch`

### PR DESCRIPTION
**Pull request by makspiechota**
Solution for https://github.com/CanonicalLtd/multipass/issues/957
1. Moved default values to constants.h, shared between daemon and cli client and used
2. Default values printed in launch help
3. Unit test to ensure cpu values are convertible to int32 added
4. clang-format applied

Note that this is my first pull to your repository (and first open source pull at all) so any comments and suggestions are appreciated

### CODE REVIEW

**Comment by Saviq** [comment]
Hi @makspiechota, thanks for helping out!

Couple of things I'd like to ask:
- could you please squash/rebase the commits so that the history isn't as complex?
- we'll need you to sign the [Canonical CLA](https://ubuntu.com/legal/contributors) to accept the change - please let us know when you've signed it (or let us know you did already, but we're missing a record of it).

Thanks again!

**Comment by makspiechota** [comment]
@Saviq Of course, I'm will rebase my commits. I need to provide project contact to sign the agreement

**Comment by makspiechota** [comment]
It seems I've messed something. I close this pull request for now

**Comment by Saviq** [comment]
@makspiechota please use me: "Michał Sawicz <michal.sawicz@canonical.com>" as the project contact.

**Pull request closed without merging**
