### PR TITLE
[release] use semantic versioning format

### PR DESCRIPTION
**Pull request by Saviq**
Adhere to https://semver.org/, using the latest tag, number of commits since
latest annotated tag and commit abbreviation as version, pre-release
identifier and build metadata, respectively.

### CODE REVIEW

**Comment by Saviq** [comment]
You'll be able to see the `-dev` version generated in travis.

To check that it works on release, use:

`git tag -as v0.6.0` - just remember to remove it then with `git tag -d v0.6.0`.

**Comment by ricab** [comment]
Oops, another review pending...

bors r-

**Comment by Saviq** [comment]
For posterity:
```
# macOS
-- Setting version to: 0.6.0-dev.238+g5c642f4
# snap
-- Setting version to: 0.6.0-dev.212+gfd9fd47
…
Snapped multipass_0.6.0-dev.212+gfd9fd47_amd64.snap
```

**Comment by Saviq** [comment]
bors r=greyback,ricab

**Pull request merged**
