### PR TITLE
Handle errors in reading/writting from/to persistent setttings

### PR DESCRIPTION
**Pull request by ricab**
This improves upon the code that was merged in #805 for #766 . I missed error handling and noticed when working on #776 .

### CODE REVIEW

**Comment by townsend2010** [comment]
Stuck

bors r-

**Comment by ricab** [comment]
bors try

**Comment by ricab** [comment]
It looks like this worked now (even though I still see status cancelled here): https://travis-ci.org/CanonicalLtd/multipass/builds/543448270

bors r=@townsend2010

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors r=townsend2010

**Comment by Saviq** [comment]
Grrh.

bors r=townsend2010

**Comment by Saviq** [comment]
bors r-

Let's try again without codecov…

bors r=townsend2010

**Pull request merged**
